# Generated by Django 3.2.7 on 2021-09-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('league_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('sport', models.CharField(max_length=100)),
                ('teams', models.CharField(blank=True, max_length=100)),
                ('players', models.CharField(blank=True, max_length=100)),
                ('Self', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(blank=True, max_length=100)),
                ('team_id', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('position', models.CharField(max_length=100)),
                ('times_trained', models.IntegerField(default=0)),
                ('league', models.CharField(blank=True, max_length=100)),
                ('team', models.CharField(blank=True, max_length=100)),
                ('self', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.TextField(blank=True)),
                ('league_id', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('league', models.CharField(blank=True, max_length=100)),
                ('players', models.CharField(blank=True, max_length=100)),
                ('self', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='greeting',
            name='when',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
